pipeline:
  docker-login:
    group: pre_build
    image: croudtech/docker-aws:latest
    pull: true
    privileged: true
    commands:
    - eval $(aws ecr get-login --no-include-email --region eu-west-2)
    - docker pull 245542037479.dkr.ecr.eu-west-2.amazonaws.com/devops/deployment-worker:latest
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  setup-image-tag:
    image: croudtech/drone-pipeline-setup:latest
    pull: true
    privileged: true
    environment:
    - DOCKER_REPO=245542037479.dkr.ecr.eu-west-2.amazonaws.com/croudtech-temp/drone-test
    - PROTECTED_FILES_LOCATION=/public/protected-files
    - PUBLIC_FOLDER=/public
    when:
      event:
      - tag
      - push
  publish-ecr:
    image: croudtech/drone-docker-ecr:latest
    repo: 245542037479.dkr.ecr.eu-west-2.amazonaws.com/croudtech-temp/drone-test
    registry: 245542037479.dkr.ecr.eu-west-2.amazonaws.com
    region: eu-west-2
    pull: true
    skip_untagged: true
    privileged: true
    when:
      event:
      - tag
      - push
  